services:
  traefik:
    image: traefik:v3.0
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /root/traefik/traefik.yml:/traefik.yml:ro
      - /root/traefik/acme.json:/letsencrypt/acme.json
    networks:
      - web

  backend-stage-0:
    build: ./backend/stage-0
    restart: unless-stopped
    environment:
      - PORT=8059
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stage-0.rule=Host(`hng14.nyagah.me`) && PathPrefix(`/api/classify`)"
      - "traefik.http.routers.stage-0.entrypoints=websecure"
      - "traefik.http.routers.stage-0.tls.certresolver=letsencrypt"
      - "traefik.http.services.stage-0.loadbalancer.server.port=8059"

  backend-stage-2:
    build: ./backend/stage-2
    restart: unless-stopped
    environment:
      - PORT=8070
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stage-2.rule=Host(`hng14.nyagah.me`) && PathPrefix(`/api/profiles`)"
      - "traefik.http.routers.stage-2.entrypoints=websecure"
      - "traefik.http.routers.stage-2.tls.certresolver=letsencrypt"
      - "traefik.http.services.stage-2.loadbalancer.server.port=8070"

volumes:
  pgdata:

networks:
  web:
    external: true
