services:
  backend-stage-0:
    build: ./backend/stage-0
    restart: unless-stopped
    ports:
      - "8059:8059"
    environment:
      - PORT=8059
    networks:
      - hng14

  backend-stage-1:
    build: ./backend/stage-1
    restart: unless-stopped
    ports:
      - "8060:8060"
    environment:
      - PORT=8060
    networks:
      - hng14

networks:
  hng14:
    driver: bridge
