services:
  traefik:
    image: traefik:v3.0
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /root/traefik/traefik.yml:/traefik.yml:ro
      - /root/traefik/acme.json:/letsencrypt/acme.json
    networks:
      - web

  stage-0:
    image: ghcr.io/tony-nyagah/hng14/stage-0:latest
    restart: unless-stopped
    environment:
      - PORT=8059
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stage-0.rule=Host(`hng14.nyagah.me`) && PathPrefix(`/api/classify`)"
      - "traefik.http.routers.stage-0.entrypoints=websecure"
      - "traefik.http.routers.stage-0.tls.certresolver=letsencrypt"
      - "traefik.http.services.stage-0.loadbalancer.server.port=8059"

  stage-1:
    image: ghcr.io/tony-nyagah/hng14/stage-1:latest
    restart: unless-stopped
    environment:
      - PORT=8060
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stage-1.rule=Host(`hng14.nyagah.me`) && PathPrefix(`/api/profiles`)"
      - "traefik.http.routers.stage-1.entrypoints=websecure"
      - "traefik.http.routers.stage-1.tls.certresolver=letsencrypt"
      - "traefik.http.services.stage-1.loadbalancer.server.port=8060"

networks:
  web:
    external: true
