import { Invoice } from './types';

// This file is auto-generated by scripts/seed.ts
export const dummyInvoices: Invoice[] = [
  {
    "id": "0CV7DW",
    "createdAt": "2025-12-18",
    "paymentDue": "2025-12-25",
    "description": "Diverse systematic success",
    "paymentTerms": 7,
    "clientName": "Oma Corwin",
    "clientEmail": "Yolanda_Morissette30@gmail.com",
    "status": "paid",
    "senderAddress": {
      "street": "2939 Hyatt Squares",
      "city": "Cincinnati",
      "postCode": "70533-3705",
      "country": "Lesotho"
    },
    "clientAddress": {
      "street": "826 Donnelly Club",
      "city": "West Tarahaven",
      "postCode": "17986-6108",
      "country": "San Marino"
    },
    "items": [
      {
        "name": "Intelligent Silk Pizza",
        "quantity": 8,
        "price": 896.19,
        "total": 7169.52
      },
      {
        "name": "Electronic Wooden Salad",
        "quantity": 10,
        "price": 274.35,
        "total": 2743.5
      }
    ],
    "total": 9913.02
  },
  {
    "id": "HMLGUF",
    "createdAt": "2025-06-23",
    "paymentDue": "2025-06-24",
    "description": "Open-source hybrid capability",
    "paymentTerms": 1,
    "clientName": "Celine Abshire",
    "clientEmail": "Norwood.Grant@yahoo.com",
    "status": "paid",
    "senderAddress": {
      "street": "824 Vicarage Close",
      "city": "Cleoboro",
      "postCode": "14830",
      "country": "Saint Lucia"
    },
    "clientAddress": {
      "street": "2659 Satterfield Plains",
      "city": "Brendaside",
      "postCode": "64687",
      "country": "Costa Rica"
    },
    "items": [
      {
        "name": "Soft Rubber Chair",
        "quantity": 1,
        "price": 87.09,
        "total": 87.09
      },
      {
        "name": "Rustic Ceramic Pants",
        "quantity": 3,
        "price": 794.69,
        "total": 2384.07
      }
    ],
    "total": 2471.1600000000003
  },
  {
    "id": "2GBSVM",
    "createdAt": "2026-01-09",
    "paymentDue": "2026-01-10",
    "description": "Programmable needs-based archive",
    "paymentTerms": 1,
    "clientName": "Antonio Mertz",
    "clientEmail": "Randal.Hayes@yahoo.com",
    "status": "paid",
    "senderAddress": {
      "street": "62420 W 1st Street",
      "city": "Beattybury",
      "postCode": "84985-6792",
      "country": "Morocco"
    },
    "clientAddress": {
      "street": "62336 Kristen Streets",
      "city": "Fort Jazlyncester",
      "postCode": "93589-7425",
      "country": "China"
    },
    "items": [
      {
        "name": "Refined Aluminum Bike",
        "quantity": 2,
        "price": 813.09,
        "total": 1626.18
      },
      {
        "name": "Unbranded Concrete Hat",
        "quantity": 5,
        "price": 430.1,
        "total": 2150.5
      },
      {
        "name": "Handcrafted Rubber Keyboard",
        "quantity": 8,
        "price": 741.1,
        "total": 5928.8
      },
      {
        "name": "Refined Concrete Pizza",
        "quantity": 4,
        "price": 608.8,
        "total": 2435.2
      }
    ],
    "total": 12140.68
  },
  {
    "id": "3ON4ZG",
    "createdAt": "2025-05-22",
    "paymentDue": "2025-06-05",
    "description": "Face to face fresh-thinking standardization",
    "paymentTerms": 14,
    "clientName": "Kayleigh Waelchi",
    "clientEmail": "Tamia_Daugherty@gmail.com",
    "status": "paid",
    "senderAddress": {
      "street": "2212 Ada Parkways",
      "city": "Glenview",
      "postCode": "82249",
      "country": "Turkey"
    },
    "clientAddress": {
      "street": "5599 E Broadway Street",
      "city": "Earnestfort",
      "postCode": "92887",
      "country": "Aruba"
    },
    "items": [
      {
        "name": "Recycled Rubber Towels",
        "quantity": 5,
        "price": 995.05,
        "total": 4975.25
      }
    ],
    "total": 4975.25
  },
  {
    "id": "QA6ZX0",
    "createdAt": "2025-04-27",
    "paymentDue": "2025-05-11",
    "description": "Triple-buffered zero defect access",
    "paymentTerms": 14,
    "clientName": "Cameron Klein II",
    "clientEmail": "Luz.Funk@gmail.com",
    "status": "paid",
    "senderAddress": {
      "street": "84066 Josefina Keys",
      "city": "Perryboro",
      "postCode": "71483",
      "country": "Albania"
    },
    "clientAddress": {
      "street": "135 Harris Parkways",
      "city": "Hintzberg",
      "postCode": "48805-9370",
      "country": "Saudi Arabia"
    },
    "items": [
      {
        "name": "Refined Metal Towels",
        "quantity": 8,
        "price": 799.89,
        "total": 6399.12
      },
      {
        "name": "Generic Metal Ball",
        "quantity": 4,
        "price": 939.65,
        "total": 3758.6
      },
      {
        "name": "Sleek Ceramic Mouse",
        "quantity": 2,
        "price": 889.89,
        "total": 1779.78
      }
    ],
    "total": 11937.5
  },
  {
    "id": "FTLE2O",
    "createdAt": "2026-04-11",
    "paymentDue": "2026-04-25",
    "description": "Polarised actuating workforce",
    "paymentTerms": 14,
    "clientName": "Alfred Sanford",
    "clientEmail": "Lauren.Koelpin@hotmail.com",
    "status": "pending",
    "senderAddress": {
      "street": "784 Lena Forks",
      "city": "Vivaboro",
      "postCode": "74785",
      "country": "Indonesia"
    },
    "clientAddress": {
      "street": "98173 Cummings Land",
      "city": "Manuelside",
      "postCode": "43479-2234",
      "country": "Anguilla"
    },
    "items": [
      {
        "name": "Intelligent Plastic Pants",
        "quantity": 6,
        "price": 864.79,
        "total": 5188.74
      }
    ],
    "total": 5188.74
  },
  {
    "id": "0QHIE1",
    "createdAt": "2025-10-27",
    "paymentDue": "2025-11-10",
    "description": "Profound fresh-thinking solution",
    "paymentTerms": 14,
    "clientName": "Dr. Joel Botsford I",
    "clientEmail": "Gustave.Schneider5@hotmail.com",
    "status": "paid",
    "senderAddress": {
      "street": "935 Washington Street",
      "city": "Lincoln",
      "postCode": "10266-5684",
      "country": "Rwanda"
    },
    "clientAddress": {
      "street": "23528 13th Street",
      "city": "Braunburgh",
      "postCode": "25263",
      "country": "France"
    },
    "items": [
      {
        "name": "Tasty Silk Soap",
        "quantity": 1,
        "price": 17.69,
        "total": 17.69
      },
      {
        "name": "Sleek Metal Chair",
        "quantity": 10,
        "price": 136.25,
        "total": 1362.5
      },
      {
        "name": "Incredible Gold Sausages",
        "quantity": 6,
        "price": 851.8,
        "total": 5110.799999999999
      }
    ],
    "total": 6490.99
  },
  {
    "id": "Q6L3LW",
    "createdAt": "2026-02-21",
    "paymentDue": "2026-02-22",
    "description": "Triple-buffered regional complexity",
    "paymentTerms": 1,
    "clientName": "Daija Adams",
    "clientEmail": "Tito_Koepp9@hotmail.com",
    "status": "draft",
    "senderAddress": {
      "street": "71582 Madisen Forges",
      "city": "East Joannycester",
      "postCode": "47757",
      "country": "Bolivia"
    },
    "clientAddress": {
      "street": "32062 Jovanny Court",
      "city": "Estellamouth",
      "postCode": "70201-2519",
      "country": "Russian Federation"
    },
    "items": [
      {
        "name": "Refined Ceramic Table",
        "quantity": 3,
        "price": 159.24,
        "total": 477.72
      },
      {
        "name": "Soft Steel Soap",
        "quantity": 6,
        "price": 692.89,
        "total": 4157.34
      },
      {
        "name": "Unbranded Silk Salad",
        "quantity": 4,
        "price": 496.89,
        "total": 1987.56
      },
      {
        "name": "Incredible Concrete Computer",
        "quantity": 4,
        "price": 566.55,
        "total": 2266.2
      }
    ],
    "total": 8888.82
  },
  {
    "id": "HORTXP",
    "createdAt": "2026-02-10",
    "paymentDue": "2026-02-11",
    "description": "Horizontal value-added matrices",
    "paymentTerms": 1,
    "clientName": "Estel Grimes",
    "clientEmail": "Domingo36@gmail.com",
    "status": "pending",
    "senderAddress": {
      "street": "60457 The Croft",
      "city": "Iowa City",
      "postCode": "61424-7814",
      "country": "Niue"
    },
    "clientAddress": {
      "street": "10668 Fritsch Wells",
      "city": "South Gate",
      "postCode": "17243",
      "country": "Dominica"
    },
    "items": [
      {
        "name": "Soft Bronze Tuna",
        "quantity": 8,
        "price": 821.29,
        "total": 6570.32
      },
      {
        "name": "Fresh Rubber Sausages",
        "quantity": 8,
        "price": 578.7,
        "total": 4629.6
      },
      {
        "name": "Bespoke Concrete Ball",
        "quantity": 4,
        "price": 723.89,
        "total": 2895.56
      },
      {
        "name": "Modern Concrete Shoes",
        "quantity": 2,
        "price": 762.95,
        "total": 1525.9
      }
    ],
    "total": 15621.38
  },
  {
    "id": "D2F4MY",
    "createdAt": "2025-11-24",
    "paymentDue": "2025-12-01",
    "description": "Persevering AI-powered moratorium",
    "paymentTerms": 7,
    "clientName": "Krystel Baumbach",
    "clientEmail": "Manuel.Rowe66@yahoo.com",
    "status": "pending",
    "senderAddress": {
      "street": "810 Lime Grove",
      "city": "North Karley",
      "postCode": "72742",
      "country": "Republic of Korea"
    },
    "clientAddress": {
      "street": "563 Frank Via",
      "city": "Lake Svenfurt",
      "postCode": "34807",
      "country": "Tokelau"
    },
    "items": [
      {
        "name": "Incredible Plastic Towels",
        "quantity": 8,
        "price": 935.05,
        "total": 7480.4
      }
    ],
    "total": 7480.4
  }
];
