import { faker } from '@faker-js/faker';
import fs from 'fs';
import path from 'path';

// Define simplified interfaces for the script
interface Address {
    street: string;
    city: string;
    postCode: string;
    country: string;
}

interface Item {
    name: string;
    quantity: number;
    price: number;
    total: number;
}

interface Invoice {
    id: string;
    createdAt: string;
    paymentDue: string;
    description: string;
    paymentTerms: number;
    clientName: string;
    clientEmail: string;
    status: 'draft' | 'pending' | 'paid';
    senderAddress: Address;
    clientAddress: Address;
    items: Item[];
    total: number;
}

const generateAddress = (): Address => ({
    street: faker.location.streetAddress(),
    city: faker.location.city(),
    postCode: faker.location.zipCode(),
    country: faker.location.country(),
});

const generateItems = (): Item[] => {
    const numItems = faker.number.int({ min: 1, max: 4 });
    const items: Item[] = [];
    for (let i = 0; i < numItems; i++) {
        const quantity = faker.number.int({ min: 1, max: 10 });
        const price = parseFloat(faker.commerce.price({ min: 10, max: 1000, dec: 2 }));
        items.push({
            name: faker.commerce.productName(),
            quantity,
            price,
            total: quantity * price,
        });
    }
    return items;
};

const generateFakeInvoice = (): Invoice => {
    const items = generateItems();
    const total = items.reduce((sum, item) => sum + item.total, 0);
    const createdAt = faker.date.past({ years: 1 });
    const paymentTerms = faker.helpers.arrayElement([1, 7, 14, 30]);
    const paymentDue = new Date(createdAt.getTime() + paymentTerms * 24 * 60 * 60 * 1000);

    return {
        id: faker.string.alphanumeric({ length: 6, casing: 'upper' }),
        createdAt: createdAt.toISOString().split('T')[0],
        paymentDue: paymentDue.toISOString().split('T')[0],
        description: faker.company.catchPhrase(),
        paymentTerms,
        clientName: faker.person.fullName(),
        clientEmail: faker.internet.email(),
        status: faker.helpers.arrayElement(['draft', 'pending', 'paid']),
        senderAddress: generateAddress(),
        clientAddress: generateAddress(),
        items,
        total,
    };
};

const invoices = Array.from({ length: 10 }, generateFakeInvoice);

const fileContent = `import { Invoice } from './types';

// This file is auto-generated by scripts/seed.ts
export const dummyInvoices: Invoice[] = ${JSON.stringify(invoices, null, 2)};
`;

const targetPath = path.resolve(__dirname, '../src/data.ts');
fs.writeFileSync(targetPath, fileContent);

console.log(`✅ Successfully generated ${invoices.length} fake invoices and saved them to src/data.ts`);
