name: Deploy to Hetzner

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: ${{ secrets.HETZNER_USER }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          script: |
            cd /root/hng14
            git pull origin main
            mkdir -p /root/traefik
            if [ -d /root/traefik/traefik.yml ]; then rm -rf /root/traefik/traefik.yml; fi
            cp /root/hng14/traefik.yml /root/traefik/traefik.yml
            touch /root/traefik/acme.json
            chmod 600 /root/traefik/acme.json
            docker compose up -d --build
